### ISSUE TITLE
Suggestion: About page

### ISSUE THREAD

**Issue by blaylockbk** [ngblaylock/scoresheet#11]
Include an "about" page with a link to the GitHub repo.

**Comment by ngblaylock** [comment]
Yep, I definitely need to sneak this in there.

**Comment by ngblaylock** [comment]
This scoresheet app was designed and developed by Nathan Blaylock. Its purpose was primarily to learn Svelte/SvelteKit and Tailwind while creating an app that would actually be used by friends and family. The app is designed primarily for mobile devices and can be "installed" by creating a shortcut on your device home screen.

Any bug fixes or suggestions can be submitted by creating an issue on [GitHub](https://github.com/ngblaylock/scoresheet/issues). 

---
Version 1.0.4 | © Nathan Blaylock 2022 | NB | GH

**Comment by ngblaylock** [comment]
Released in v1.0.4
